
mutation EmailAndPasswordLoginBoard($input: LoginBoardInput!) {
    emailAndPasswordLoginBoard(input: $input) {
      data {
        id
        email
        token
      }
      code
      success
      message
    }
  }


query getUsersBoard($filter: UsersBoardFilter!, $paginate: PaginatorInput, $sortBy: UsersBoardSortEnum) {
    usersBoard(filter: $filter, paginate: $paginate, sortBy: $sortBy) {
    data{
        items{
          firstName
          nickname
          birthDate
          age
          gender
          email
          city {
            id
          }
        }
      }
      code
      success
      message
    }
    }

query countries{
  countries{
    data{
      id
      enName
    }
  }
}


    
mutation createUserBoard($input: CreateUserBoardInput!) {
  createUserBoard(input: $input) {
    data {
      id
      firstName
      lastName
      email
      birthDate
      nationality{
        id
      }
      gender{
        MALE
        FEMALE
        NOANSWER
      }
      phone
    }     
    code
    success
    message
  }
}

mutation updateUserBoard($input: UpdateUserBoardInput!) {
  updateUserBoard(input: $input) {
    data {
      id
      firstName
      enLastName
      email
      birthDate
      nationality{
        id
      }
      gender
      phone
    }     
    code
    success
    message
  }
}

