
mutation EmailAndPasswordLoginBoard($input: LoginBoardInput!) {
    emailAndPasswordLoginBoard(input: $input) {
      data {
        id
        email
        token
      }
      code
      success
      message
    }
  }


query getUsersBoard(
  $filter: UsersBoardFilter! = {}
  $paginate: PaginatorInput
  $sortBy: UsersBoardSortEnum
) {
  usersBoard(filter: $filter, paginate: $paginate, sortBy: $sortBy) {
    data {
      items {
        id
        firstName
        nickname
        enLastName
        birthDate
        phone
        nationality {
          id
          enName
          isoCode
        }
        age
        gender
        email
        city {
          id
        }
      }
    }
    code
    success
    message
  }
}



query countries ($enableCities: Boolean) {
        countries(enableCities: $enableCities) {
          data {
            id
            enName
          }
          code
          success
          message
        }
      }


mutation createUserBoard($input: CreateUserBoardInput!) {
  createUserBoard(input: $input) {
    data {
      id
      firstName
      enLastName
      email
      birthDate
      nationality{
        id
        enName
      }
      gender
      phone
    }     
    code
    success
    message
  }
}


mutation updateUserBoard($input: UpdateUserBoardInput!) {
  updateUserBoard(input: $input) {
    data {
      id
      firstName
      enLastName
      gender
      birthDate
      age
      nationality{
        id
        enName
      }
      phone
      email
    }     
    code
    success
    message
  }
}

mutation deleteUserBoard($userId: ID!) {
  deleteUserBoard(userId: $userId) {
    data
    code
    success
    message
  }
}

query admin{
  me{
    data{
      id
    }
  }
}


